### ISSUE TITLE
Too many IDs

### ISSUE THREAD

**Issue by ghost** [AllTheLayers/ATLCraftCandlesMod#12]
Loving this mod very much, but I cannot use it in 2 of my modpacks because it uses up too many IDs.
Granted, other mods also use a lot, but when trying to find a solution for my 'too many IDs error' it always seems to boil down to this mod pushing it over the edge so to speak.
Would it be possible (and perhaps better) to not give each model variation its own ID number but NBT-data instead?

**Comment by AllTheLayers** [comment]
It's definitely possible to use NBT data instead of block IDs. I should have used it from the beginning, however, because now it would need large parts of it to be re-written which is time consuming. Also, it would remove almost all of the candles in worlds that currently have the mod installed.

The update to Minecraft 1.13 is supposed to remove the block ID limit, and this will no longer be an issue. For now, you could use another mod like NotEnoughIDs to increase your block ID limit.

**Comment by ghost** [comment]
You are right, I totally forgot 1.13 will solve this.
